# Generated by Django 5.1.7 on 2025-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
                ('week', models.PositiveIntegerField(editable=False)),
                ('day', models.PositiveIntegerField(editable=False)),
                ('hour', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['year', 'month'], name='mapp_scanlo_year_2eb764_idx'), models.Index(fields=['year', 'week'], name='mapp_scanlo_year_0fde33_idx'), models.Index(fields=['year', 'day'], name='mapp_scanlo_year_326d85_idx'), models.Index(fields=['year', 'hour'], name='mapp_scanlo_year_543a95_idx')],
            },
        ),
    ]
