# Generated by Django 5.1.7 on 2025-11-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_scanlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScanLog',
            new_name='ErrorLog',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='mapp_errorl_year_c4c2bd_idx',
            old_name='mapp_scanlo_year_2eb764_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='mapp_errorl_year_cdce60_idx',
            old_name='mapp_scanlo_year_0fde33_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='mapp_errorl_year_57fc83_idx',
            old_name='mapp_scanlo_year_326d85_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='mapp_errorl_year_42b11d_idx',
            old_name='mapp_scanlo_year_543a95_idx',
        ),
    ]
