# Generated by Django 5.1.7 on 2025-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_statutorydeduction_systemsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification_photos/'),
        ),
    ]
