# Generated by Django 5.1.7 on 2025-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_attendancesession_clock_in_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('subordinate', 'Subordinate Staff')], default='staff', max_length=20),
        ),
    ]
