# Generated by Django 5.1.7 on 2025-12-02 14:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_workinghoursconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate_currency',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
