# Generated by Django 5.1.7 on 2025-12-04 19:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_customuser_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='overtimeallowance',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='advancepayment',
            name='mapp_advanc_user_id_00e835_idx',
        ),
        migrations.RemoveIndex(
            model_name='overtimeallowance',
            name='mapp_overti_user_id_3a8708_idx',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='year',
        ),
        migrations.RemoveField(
            model_name='overtimeallowance',
            name='approved_flag',
        ),
        migrations.RemoveField(
            model_name='overtimeallowance',
            name='date',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimeallowance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='overtimeallowance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['user', 'created_at'], name='mapp_advanc_user_id_47fe53_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeallowance',
            index=models.Index(fields=['user', 'created_at'], name='mapp_overti_user_id_0f80a7_idx'),
        ),
    ]
