# Generated by Django 5.1.7 on 2025-12-04 20:37

import django.utils.timezone
import mapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_alter_advancepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancepayment',
            options={'ordering': ['-year', '-month', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='advancepayment',
            name='mapp_advanc_user_id_47fe53_idx',
        ),
        migrations.RemoveIndex(
            model_name='overtimeallowance',
            name='mapp_overti_user_id_0f80a7_idx',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='month',
            field=models.PositiveSmallIntegerField(default=mapp.models.current_month),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='year',
            field=models.PositiveSmallIntegerField(default=mapp.models.current_year),
        ),
        migrations.AddField(
            model_name='overtimeallowance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='overtimeallowance',
            name='month',
            field=models.PositiveSmallIntegerField(default=mapp.models.current_month),
        ),
        migrations.AddField(
            model_name='overtimeallowance',
            name='year',
            field=models.PositiveSmallIntegerField(default=mapp.models.current_year),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['user', 'year', 'month'], name='mapp_advanc_user_id_00e835_idx'),
        ),
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['year', 'month'], name='mapp_advanc_year_68c147_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeallowance',
            index=models.Index(fields=['user', 'year', 'month'], name='mapp_overti_user_id_ef4ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimeallowance',
            index=models.Index(fields=['year', 'month'], name='mapp_overti_year_801b5b_idx'),
        ),
    ]
