# Generated by Django 5.1.7 on 2025-12-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_alter_advancepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('office', 'Office'), ('teaching', 'Teaching'), ('subordinate', 'Subordinate')], default='staff', max_length=20),
        ),
    ]
