# Generated by Django 5.1.7 on 2025-12-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='noname', max_length=150),
            preserve_default=False,
        ),
    ]
