# Generated by Django 5.1.7 on 2025-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0013_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('office', 'Office'), ('teaching', 'Teaching'), ('subordinate', 'Subordinate')], default='subordinate', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
