# Generated by Django 5.1.7 on 2025-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0014_alter_customuser_email_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_on_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
