# Generated by Django 5.1.7 on 2025-12-14 20:42

import django.db.models.deletion
import django.utils.timezone
import mapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0015_customuser_is_on_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourCorrection',
            fields=[
                ('correction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.PositiveSmallIntegerField(default=mapp.models.current_month)),
                ('year', models.PositiveSmallIntegerField(default=mapp.models.current_year)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hour_corrections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='mapp_hourco_user_id_cbe2f1_idx'), models.Index(fields=['year', 'month'], name='mapp_hourco_year_9306c8_idx')],
            },
        ),
    ]
