# Generated by Django 5.1.7 on 2025-12-14 20:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0016_hourcorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourcorrection',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='hourcorrection',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
