# Generated by Django 5.1.7 on 2025-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0017_alter_hourcorrection_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('super', 'Super Admin'), ('admin', 'Admin'), ('office', 'Office'), ('teaching', 'Teaching'), ('subordinate', 'Subordinate')], default='subordinate', max_length=20),
        ),
    ]
