# Generated by Django 5.1.7 on 2025-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0018_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lunch_end',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lunch end time in 24hr format e.g. 1400', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lunch_start',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lunch start time in 24hr format e.g. 1300', null=True),
        ),
    ]
