# Generated by Django 5.1.7 on 2025-12-16 12:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0019_customuser_lunch_end_customuser_lunch_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRateSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hourly_rate_snapshots', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rate_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['user', 'effective_from'], name='mapp_hourly_user_id_d7e57d_idx')],
            },
        ),
    ]
