# Generated by Django 5.1.7 on 2025-12-16 13:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0020_hourlyratesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryDeductionSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_statutory_deduction_snapshots', to=settings.AUTH_USER_MODEL)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='mapp.statutorydeduction')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['deduction', 'effective_from'], name='mapp_statut_deducti_ae3f34_idx')],
            },
        ),
    ]
