# Generated by Django 5.1.7 on 2025-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0021_statutorydeductionsnapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghoursconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workinghoursconfig',
            name='user_role',
            field=models.CharField(choices=[('super', 'Super Admin'), ('admin', 'Admin'), ('office', 'Office'), ('teaching', 'Teaching'), ('subordinate', 'Subordinate')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workinghoursconfig',
            unique_together={('day_of_week', 'user_role', 'timezone')},
        ),
    ]
