# Generated by Django 5.1.7 on 2025-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0022_alter_workinghoursconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghoursconfig',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('office', 'Office'), ('teaching', 'Teaching'), ('subordinate', 'Subordinate')], max_length=20),
        ),
    ]
