# Generated by Django 5.1.7 on 2025-12-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0023_alter_workinghoursconfig_user_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancesession',
            name='mapp_attend_user_id_eb4af1_idx',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='clockin_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('overtime', 'Overtime')], default='regular', max_length=15),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['user', 'date', 'clockin_type'], name='mapp_attend_user_id_4fc386_idx'),
        ),
    ]
