# Generated by Django 5.1.7 on 2025-12-30 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0024_remove_attendancesession_mapp_attend_user_id_eb4af1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetail',
            fields=[
                ('org_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name of Organization')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
