# Generated by Django 5.1.7 on 2025-12-31 10:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0025_organizationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nssf_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly NSSF contribution amount', max_digits=10),
        ),
    ]
