# Generated by Django 5.1.7 on 2026-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0026_customuser_nssf_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationdetail',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
