# Generated by Django 5.1.7 on 2026-02-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0027_customuser_kra_pin_organizationdetail_kra_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='clock_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
