# Generated by Django 5.1.7 on 2026-02-28 12:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0028_attendancesession_clock_out_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateArrival',
            fields=[
                ('late_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('session', models.CharField(choices=[('first', 'First'), ('second', 'Second')], db_index=True, default='first', max_length=10)),
                ('lateness_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hours late. Decimals allowed (e.g., 0.25 = 15 minutes).', max_digits=6)),
                ('expected_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('excused_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lateness_excused_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_arrivals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='mapp_latear_user_id_9fbb9c_idx'), models.Index(fields=['date', 'session'], name='mapp_latear_date_9d806c_idx'), models.Index(fields=['is_excused', 'date'], name='mapp_latear_is_excu_3ee33c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'session'), name='uniq_latearrival_user_date_session')],
            },
        ),
    ]
