# Generated by Django 5.1.7 on 2026-03-08 20:36

import mapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0029_latearrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='day',
            field=models.PositiveSmallIntegerField(default=mapp.models.current_day),
        ),
        migrations.AddField(
            model_name='hourcorrection',
            name='day',
            field=models.PositiveSmallIntegerField(default=mapp.models.current_day),
        ),
    ]
