# Generated by Django 5.1.7 on 2026-03-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0030_advancepayment_day_hourcorrection_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancepayment',
            options={'ordering': ['-year', '-month', '-day', '-created_at']},
        ),
    ]
